// Candidate source URLs for triage by `npx tsx scripts/probe.ts`.
//
// This is the raw universe of UK / London sources we consider. The probe sorts
// them into static-fetchable vs JS-rendered; the sorted result is what lands in
// `lib/sources/index.ts` as the live registry. Keeping the raw list checked in
// means re-triaging after a site redesign is one command.

export const CANDIDATE_URLS: { name: string; url: string }[] = [
  // --- News / publications (RSS) -------------------------------------------
  { name: "UKTN", url: "https://www.uktech.news/feed" },
  { name: "Sifted", url: "https://sifted.eu/feed" },
  { name: "Tech.eu", url: "https://tech.eu/feed/" },
  { name: "EU-Startups", url: "https://www.eu-startups.com/feed/" },
  { name: "Maddyness UK", url: "https://www.maddyness.com/uk/feed/" },
  { name: "BusinessCloud", url: "https://businesscloud.co.uk/feed/" },
  { name: "Startups Magazine", url: "https://startupsmagazine.co.uk/feed" },
  { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
  { name: "Silicon Canals", url: "https://siliconcanals.com/feed/" },
  { name: "TechRound", url: "https://techround.co.uk/feed/" },

  // --- VC portfolios --------------------------------------------------------
  { name: "Northzone", url: "https://northzone.com/portfolio/" },
  { name: "LocalGlobe", url: "https://localglobe.vc/localglobe/companies" },
  { name: "Phoenix Court", url: "https://phoenixcourt.com/portfolio/" },
  { name: "Seedcamp", url: "https://seedcamp.com/companies/" },
  { name: "Balderton", url: "https://www.balderton.com/companies/" },
  { name: "Atomico", url: "https://www.atomico.com/portfolio" },
  { name: "Index Ventures", url: "https://www.indexventures.com/companies/" },
  { name: "Accel", url: "https://www.accel.com/companies" },
  { name: "Hoxton Ventures", url: "https://hoxtonventures.com/portfolio/" },
  { name: "Concept Ventures", url: "https://www.conceptventures.vc/portfolio" },
  { name: "Episode 1", url: "https://episode1.com/portfolio/" },
  { name: "Ada Ventures", url: "https://www.adaventures.com/categories/portfolio" },
  { name: "Playfair Capital", url: "https://playfair.vc/portfolio.php" },
  { name: "Amadeus Capital", url: "https://www.amadeuscapital.com/our-companies/" },
  { name: "IQ Capital", url: "https://www.iqcapital.vc/companies" },
  { name: "Octopus Ventures", url: "https://octopusventures.com/portfolio/" },
  { name: "MMC Ventures", url: "https://mmc.vc/portfolio/" },
  { name: "Dawn Capital", url: "https://dawncapital.com/companies" },
  { name: "Air Street Capital", url: "https://www.airstreet.com/portfolio" },
  { name: "Kindred Capital", url: "https://kindredcapital.vc/portfolio/" },
  { name: "Passion Capital", url: "https://passioncapital.com/fund-portfolio/" },
  { name: "firstminute capital", url: "https://www.firstminute.capital/portfolio" },
  { name: "Fuel Ventures", url: "https://fuel.ventures/portfolio/" },
  { name: "SFC Capital", url: "https://sfccapital.com/portfolio/" },
  { name: "Molten Ventures", url: "https://www.moltenventures.com/portfolio/" },
  { name: "Eka Ventures", url: "https://www.ekavc.com/portfolio" },
  { name: "Connect Ventures", url: "https://www.connectventures.co.uk/portfolio" },
  { name: "Frontline Ventures", url: "https://frontline.vc/companies/" },
  { name: "AlbionVC", url: "https://albion.vc/portfolio/" },
  { name: "Notion Capital", url: "https://notion.vc/portfolio/" },
  { name: "83North", url: "https://www.83north.com/companies/" },
  { name: "Felix Capital", url: "https://www.felixcap.com/portfolio" },
  { name: "Latitude", url: "https://latitude.vc/latitude/companies" },

  // --- Accelerators / studios ----------------------------------------------
  { name: "Entrepreneur First", url: "https://www.joinef.com/companies/" },
  { name: "Founders Factory", url: "https://foundersfactory.com/portfolio/" },
  { name: "Antler UK", url: "https://www.antler.co/portfolio" },
  { name: "Techstars London", url: "https://www.techstars.com/portfolio" },
  { name: "Bethnal Green Ventures", url: "https://bethnalgreenventures.com/portfolio/" },
  { name: "Carbon13", url: "https://carbonthirteen.com/ventures/" },
  { name: "Zinc VC", url: "https://www.zinc.vc/portfolio-companies/" },
  { name: "Conception X", url: "https://www.conceptionx.org/portfolio" },

  // --- University / deep tech spinouts -------------------------------------
  { name: "Oxford Science Enterprises", url: "https://oxfordscienceenterprises.com/portfolio/" },
  { name: "Cambridge Enterprise", url: "https://www.enterprise.cam.ac.uk/portfolio/" },
  { name: "UCL Business", url: "https://www.uclb.com/spinout-portfolio" },
  { name: "Deep Science Ventures", url: "https://deepscienceventures.com/our-portfolio" },
  { name: "Parkwalk Advisors", url: "https://parkwalkadvisors.com/portfolio/" },
  // --- Second wave: further UK / London funds --------------------------------
  { name: "Crane Venture Partners", url: "https://crane.vc/portfolio/" },
  { name: "Moonfire Ventures", url: "https://www.moonfire.com/portfolio" },
  { name: "Backed VC", url: "https://backed.vc/portfolio" },
  { name: "Stride VC", url: "https://stride.vc/portfolio" },
  { name: "Anthemis", url: "https://www.anthemis.com/portfolio/" },
  { name: "Augmentum Fintech", url: "https://www.augmentum.vc/portfolio/" },
  { name: "Hambro Perks", url: "https://hambroperks.com/portfolio/" },
  { name: "Northern Gritstone", url: "https://northerngritstone.com/portfolio/" },
  { name: "Ahren Innovation Capital", url: "https://www.ahreninnovation.com/portfolio" },
  { name: "Lakestar", url: "https://www.lakestar.com/portfolio" },
  { name: "Speedinvest", url: "https://www.speedinvest.com/portfolio" },
  { name: "Entree Capital", url: "https://www.entree.vc/portfolio" },
  { name: "Oxford Capital", url: "https://oxcp.com/portfolio/" },
  { name: "Mercia Ventures", url: "https://www.mercia.co.uk/portfolio/" },
  { name: "Praetura Ventures", url: "https://praetura.co.uk/portfolio/" },
  { name: "Form Ventures", url: "https://www.form.vc/portfolio" },
  { name: "Ascension", url: "https://ascension.vc/portfolio/" },
  { name: "Triple Point Ventures", url: "https://www.triplepoint.co.uk/ventures/portfolio/" },
  { name: "Haatch", url: "https://haatch.com/portfolio/" },
  { name: "JamJar Investments", url: "https://www.jamjarinvestments.com/portfolio" },
  { name: "Sure Valley Ventures", url: "https://surevalleyventures.com/portfolio/" },
  { name: "LocalGlobe Latitude", url: "https://latitude.vc/latitude/companies" },
  { name: "Illuminate Financial", url: "https://illuminate.financial/portfolio/" },
  { name: "AENU", url: "https://www.aenu.com/portfolio" },
  { name: "Emerge Education", url: "https://emerge.education/portfolio/" },
  { name: "Mustard Seed Maze", url: "https://www.mustardseedmaze.vc/portfolio" },
  { name: "SuperSeed", url: "https://superseed.com/portfolio/" },
  { name: "Fern Ventures", url: "https://fern.vc/portfolio" },
  { name: "Sustainable Ventures", url: "https://www.sustainableventures.co.uk/portfolio" },
  { name: "Founders Intelligence", url: "https://www.foundersfactory.com/portfolio/" },
];
